config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'invoice_dashboard#index', as: :authenticated_root
  end

  root to: "accounting#index"

  devise_for :users

  resources :general_expenses, only: [:index] do
    collection do
      get 'active_invoices' => 'general_expenses#active_invoices'
      get 'passive_invoices' => 'general_expenses#passive_invoices'
    end
  end

  resources :fuel_receipts

  resources :invoices, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'invoice_dashboard#index'
      get 'active' => 'invoice_dashboard#active_invoices'
      get 'passive' => 'invoice_dashboard#passive_invoices'
    end

    resources :payments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :insurances do
    resources :receipts, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tickets do
    collection do
      get 'administrative_dashboard' => 'tickets_dashboard#administrative'
      get 'vehicle_dashboard' => 'tickets_dashboard#vehicle'
    end
  end

  resources :categories, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'category_dashboard#index'
    end
    member do
      get 'insurances' => 'insurance_dashboard#category_insurances'
      get 'dashboard' => 'category_dashboard#show'
      get 'passive_invoices' => 'category_dashboard#passive_invoices'
      get 'active_invoices' => 'category_dashboard#active_invoices'
    end
  end

  resources :companies do
    collection do
      get 'dashboard' => 'company_dashboard#index'
    end
    member do
      get 'dashboard' => 'company_dashboard#show'
      get 'insurances' => 'insurance_dashboard#company_insurances'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#company_receipts'
      get 'passive_invoices' => 'company_dashboard#passive_invoices'
      get 'active_invoices' => 'company_dashboard#active_invoices'
    end
  end

  resources :vehicles, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'vehicle_dashboard#index'
    end
    member do
      get 'dashboard' => 'vehicle_dashboard#show'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#vehicle_receipts'
      get 'passive_invoices' => 'vehicle_dashboard#passive_invoices'
      get 'active_invoices' => 'vehicle_dashboard#active_invoices'
    end
  end
end

app/models/insurance.rb
class Insurance < ActiveRecord::Base
  belongs_to :user
  belongs_to :vehicle
  belongs_to :company
  has_many :receipts, dependent: :destroy

  validates :total, presence: { message: "Inserire l'ammontare del contratto assicurativo" }
  validates :company_id, presence: { message: "Selezionare l'azienda la quale ha emesso o ricevuto la assicurazione" }
  validates :at_the_expense_of, presence: { message: 'Selezionare a carrico di cosa e registrata la assicurazione' }
  validates :serial_of_contract, presence: { message: 'Inserire il numero del contratto' }
  validates :date_of_issue, presence: { message: 'Selezionare data di emissione' }
  validates :recurrence, presence: { message: 'Selezionare la riccorrenza' }
  validates :deadline, presence: { message: 'Selezionare data di scadenza' }

  def payment_date
    due_date = self.date_of_issue
    until due_date > Time.zone.now do
      self.recurrence == 12 ? due_date += 1.year : due_date += self.recurrence.months
    end
    due_date.strftime('%d-%m-%Y')
  end

  def self.month(month = time_now)
    where('date_of_issue >= ? and date_of_issue <= ?', month.beginning_of_month, month.end_of_month)
  end

  def self.year(year = time_now)
    where('date_of_issue >= ? and date_of_issue <= ?', year.beginning_of_year, year.end_of_year)
  end

  def company_name
    company.name
  end

  def vehicle_plate
    vehicle.plate
  end

  def self.total_all
    sum(:total).round(2)
  end

  def total_receipts
    receipts.sum(:paid).round(2)
  end

  def self.active
    find_by('date_of_issue <= ? and deadline >= ?', time_now, time_now)
  end

  def self.general_insurances(user_id)
    where('date_of_issue <= ? and deadline >= ?', time_now, time_now).
      where(at_the_expense_of: 'general_insurance').where(user_id: user_id)
  end

  def self.general_insurances_total(user_id)
    general_insurances(user_id).sum(:total)
  end

  def self.total_all_receipts
    total = 0
    self.all.each do |insurance|
      total += insurance.receipts.sum(:paid)
    end
    total
  end

  def self.time_now
    Time.zone.now
  end
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
  before_action :authenticate_user!
  before_action :vehicle_general_expences_any?
  before_action :insurance_category_any?
  before_action :insurance_company_any?

  def index
    @companies = current_user_companies.insurances
  end

  def show
    @insurance = Insurance.find(params[:id])
  end

  def new
    @insurance = Insurance.new
    @companies = current_user_companies.insurances
    @vehicles = current_user_vehicles
  end

  def create
    build_params = build_insurance
    @insurance = Insurance.new(build_params)
    @companies = current_user_companies.insurances
    @vehicles = current_user_vehicles
    if @insurance.save
      flash[:success] = 'Contratto assicurativo registrato'
      redirect_to insurance_path(@insurance.id)
    else
      render 'new'
    end
  end

  def edit
    @insurance = Insurance.find(params[:id])
    @companies = current_user_companies.insurances
    @vehicles = current_user_vehicles
  end

  def update
    build_params = build_insurance
    @insurance = Insurance.find(params[:id])
    @companies = current_user_companies.insurances
    @vehicles = current_user_vehicles
    if @insurance.update(build_params)
      flash[:success] = 'Contratto assicurativo aggiornato'
      redirect_to insurance_path(@insurance.id)
    else
      render 'edit'
    end
  end

  def destroy
    insurance = Insurance.find(params[:id])
    insurance.destroy
    flash[:success] = 'Contratto assicurativo elliminato'
    redirect_after_destroy(current_user_insurances)
  end

  private

  def build_insurance
    BuildInsurance.new(insurance_params_user_id).build
  end

  def insurance_params
    params.require(:insurance).permit(:total, :at_the_expense_of, :vehicle_id, :serial_of_contract, :company_id, :description, :deadline, :date_of_issue, :recurrence)
  end

  def insurance_params_user_id
    insurance_params.merge!(user_id: current_user.id)
  end
end

app/views/insurances/_form.html.erb
<div class="row">
  <div class="new">
    <%= form_for insurance do |form| %>
      <% if insurance.errors.any? %>
        A causa di questi errori non e' stato possibile creare la fattura:
        <ul>
          <% insurance.errors.messages.each do |name, error| %>
            <li><%= error[0] %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Totale' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :total, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Numero poliza' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :serial_of_contract, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Azienda' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.collection_select(:company_id, @companies, :id, :name, prompt: "Aziende") %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'A carico di' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.select(:at_the_expense_of, class: 'at_the_expense_of') do %>
            <%= options_for_select([['Slezionare valore', nil], ['Tutti i veicoli', 'general_insurance'], ['Veicolo specifico', 'specific_vehicle']], selected: form.object.at_the_expense_of) %>
          <% end %>
        </div>
      </div>
      <div id='vehicles'>
        <%= select_specific_vehicle(insurance, form) %>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Descrizione' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :description %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Data emissione fattura' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :date_of_issue, class: 'date', placeholder: "Selezionare data...", require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Data scadenza' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :deadline, class: 'date', placeholder: "Selezionare data...", require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Riccorenza' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.select(:recurrence, options_for_select([["Ogni mese", 1], ["Bimestrale", 2], ["Trimestrale", 3], ["Quadrimestrale", 4], ["Semestrale", 6], ["Anuale", 12]], selected: form.object.recurrence )) %>
        </div>
      </div>
      <div class="row">
        <div class="col span-3-of-3 submit">
          <%= form.submit "Conferma", class: "btn btn-big" %>
        </div>
      </div>
      <script type="text/javascript">
        $(function(){
          $(document).on('change', '#insurance_at_the_expense_of', function(){
            var val = $(this).val();
            $('#vehicles').empty();
            if(val === 'specific_vehicle'){
              $('#vehicles').html("<%=escape_javascript( render 'vehicles/specific_vehicles', form: form ) %>");
            }
          });
        });
      </script>
    <% end %>
  </div>
</div>

app/views/insurances/_insurance.html.erb
<tbody>
  <tr>
    <td id="supplier_<%=insurance.company_id%>"><%= link_to insurance.company_name, company_path(insurance.company_id) %></td>
    <td id="total_<%=insurance.company_id%>"><%= insurance.total %></td>
    <td class="paid"><%= insurance.total_receipts %></td>
    <td><%= link_to insurance.description, insurance_path(id: insurance.id) %></td>
    <td class="at-the-expense-of"><%= link_to_at_the_expense_of(insurance) %></td>
    <td class="deadline"><%= insurance.deadline.strftime("%d-%m-%Y")%></td>
    <td class="cash-insurance">
      <%= link_to new_insurance_receipt_path(insurance_id: insurance.id) do %>
        <i class="ion-cash icon-small-cash"></i>
      <% end%>
    </td>
    <td class="delete-insurance_<%=insurance.id%>">
      <%= link_to insurance_path(id: insurance.id), method: :delete, data: {confirm: "Si e sicuri?"} do%>
        <i class="ion-ios-trash icon-small-trash"></i>
      <% end%>
    </td>
  </tr>
</tbody>

app/views/insurances/edit.html.erb
<div class="row">
  <div class="new">
    <h3>Modifica contratto assicurativo</h3>
  </div>
</div>
<%= render 'form', insurance: @insurance %>

app/views/insurances/index.html.erb
<div class="row">
  <div class="companies">
    <%= render partial: 'companies/insurance_companies', collection: @companies, as: :company %>
  </div>
</div>

app/views/insurances/new.html.erb
<div class="row">
<div class="new">
	<h3>Aggiungi contratto assicurativo</h3>
</div>
</div>
<%= render 'form', insurance: @insurance %>

app/views/insurances/show.html.erb
<div class="row">
  <div class="invoice-show-title">
    <h2 id="company_name"><%= @insurance.company_name %></h2>
    <div class="title">
      <h3><%= @insurance.serial_of_contract %></h3>
      <%= link_to edit_insurance_path(insurance_id: @insurance.id), class: 'edit-insurance', title: "Modifica contratto assicurativo." do %>
        <i class="ion-ios-compose icon-small-compose"></i>
      <% end %>
      <%= link_to new_insurance_receipt_path(insurance_id: @insurance.id), class: 'pay-insurance' do %>
        <i class="ion-cash icon-small-cash"></i>
      <% end%>
    </div>
  </div>
  <div class="invoice-show">
    <div class="row">
      <div class="col span-1-of-2">
        <h4>Numero poliza:</h4>
      </div>
      <div class="col span-1-of-2 data">
        <p id='serial_of_contract'><%=@insurance.serial_of_contract%></p>
      </div>
    </div>
    <div class="row">
      <div class="col span-1-of-2">
        <h4>Totale:</h4>
      </div>
      <div class="col span-1-of-2 data">
        <p id='total_insurance'><%=@insurance.total%></p>
      </div>
    </div>
    <div class="row">
      <div class="col span-1-of-2">
        <h4>A carrico di:</h4>
      </div>
      <div class="col span-1-of-2 data">
        <p id='vehicle_plate'><%=link_to_at_the_expense_of(@insurance) %></p>
      </div>
    </div>
    <div class="row">
      <div class="col span-1-of-2">
        <h4>Ricorrenza:</h4>
      </div>
      <div class="col span-1-of-2 data">
        <p><%=@insurance.recurrence %></p>
      </div>
    </div>
    <% if @insurance.description %>
      <div class="row">
        <div class="col span-1-of-2">
          <h4>Descrizione:</h4>
        </div>
        <div class="col span-1-of-2 data">
          <p><%=@insurance.description %></p>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col span-1-of-2">
        <h4>Data emissione:</h4>
      </div>
      <div class="col span-1-of-2 data">
        <p><%=@insurance.date_of_issue.strftime("%d-%m-%Y") %></p>
      </div>
    </div>
    <div class="row">
      <div class="col span-1-of-2">
        <h4>Data scadenza:</h4>
      </div>
      <div class="col span-1-of-2 data">
        <p><%=@insurance.deadline.strftime("%d-%m-%Y") %></p>
      </div>
    </div>
    <%unless @insurance.receipts.empty? %>
      <h2>Ricevute di pagamento</h2>
      <%= render @insurance.receipts, insurance: @insurance %>
    <%end%>
  </div>
</div>