config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'invoice_dashboard#index', as: :authenticated_root
  end

  root to: "accounting#index"

  devise_for :users

  resources :general_expenses, only: [:index] do
    collection do
      get 'active_invoices' => 'general_expenses#active_invoices'
      get 'passive_invoices' => 'general_expenses#passive_invoices'
    end
  end

  resources :fuel_receipts

  resources :invoices, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'invoice_dashboard#index'
      get 'active' => 'invoice_dashboard#active_invoices'
      get 'passive' => 'invoice_dashboard#passive_invoices'
    end

    resources :payments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :insurances do
    resources :receipts, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tickets do
    collection do
      get 'administrative_dashboard' => 'tickets_dashboard#administrative'
      get 'vehicle_dashboard' => 'tickets_dashboard#vehicle'
    end
  end

  resources :categories, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'category_dashboard#index'
    end
    member do
      get 'insurances' => 'insurance_dashboard#category_insurances'
      get 'dashboard' => 'category_dashboard#show'
      get 'passive_invoices' => 'category_dashboard#passive_invoices'
      get 'active_invoices' => 'category_dashboard#active_invoices'
    end
  end

  resources :companies do
    collection do
      get 'dashboard' => 'company_dashboard#index'
    end
    member do
      get 'dashboard' => 'company_dashboard#show'
      get 'insurances' => 'insurance_dashboard#company_insurances'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#company_receipts'
      get 'passive_invoices' => 'company_dashboard#passive_invoices'
      get 'active_invoices' => 'company_dashboard#active_invoices'
    end
  end

  resources :vehicles, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'vehicle_dashboard#index'
    end
    member do
      get 'dashboard' => 'vehicle_dashboard#show'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#vehicle_receipts'
      get 'passive_invoices' => 'vehicle_dashboard#passive_invoices'
      get 'active_invoices' => 'vehicle_dashboard#active_invoices'
    end
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :invoices, dependent: :destroy
  has_many :fuel_receipts, dependent: :destroy
  has_many :insurances, dependent: :destroy

  phony_normalize :number, default_country_code: 'IT'
  validates :name, presence: { message: "Inserire nome dell'azienda" }
  validates :adress, presence: { message: "Inserire indirizzo dell'azienda" }
  validates :number, presence: { message: "Inserire numero telefonico dell'azienda" }
  validates :category_id, presence: { message: "Selezionare categoria dell'azienda" }

  def vehicles_insured
    Vehicle.joins(insurances: :company).uniq
  end

  def vehicles_refueling
    Vehicle.joins(fuel_receipts: :company).uniq
  end

  def calculator
    Calculator.new
  end

  def self.gas_stations
    where(category_id: Category.gas_station_id)
  end

  def self.insurances
    where(category_id: Category.insurance_id)
  end

  def insurance?
    true if category.type_of == 3
  end

  def category_name
    category.name
  end

  def fuel_receipts_total
    fuel_receipts.sum(:total).round(2)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :category_any?

  def index
    @companies = current_user.companies
  end

  def new
    @category = current_user.categories
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
    @category = current_user.categories
  end

  def update
    @company  = Company.find(params[:id])
    @category = current_user.categories
    if @company.update(company_params)
      flash[:success] = 'Azienda aggiornata'
      redirect_to dashboard_companies_path
    else
      render 'edit'
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.destroy
    flash[:success] = 'Azienda elliminata'
    redirect_after_destroy(current_user_companies)
  end

  def show
    @company = Company.find(params[:company_id] || params[:id])
  end

  def create
    @company = Company.new(company_params_user_id)
    @category = current_user_categories
    if @company.save
      flash[:success] = 'Azienda aggiunta'
      redirect_to dashboard_companies_path
    else
      render 'new'
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :adress, :number, :category_id)
  end

  def company_params_user_id
    company_params.merge!(user_id: current_user[:id])
  end

  def company
    @_company ||= Company.find(params[:id])
  end

  def category_id
    company_params[:category_id]
  end
end

app/views/companies/_company.html.erb
<div class="col span-1-of-3 summary">
  <div class="title">
    <h2 id="company_name"><%=link_to company.name, company_path(company.id) %></h2>
  </div>
  <br>
  <%= link_to edit_company_path(company.id), class: 'edit-company', title: "Modifica azienda." do %>
    <i class="ion-ios-compose icon-small-compose"></i>
  <% end %>
  <%= link_to company_path(company.id), class: 'delete-company', title: "Elimina azienda." , method: :delete, data: {confirm: "L'elliminazione di questo veicolo elliminera automaticamente anche le fatture registrate su di esso, si e sicuri di volerlo elliminare?"} do%>
    <i class="ion-ios-trash icon-small-trash"></i>
  <% end %>
  <% if company.insurance? %>
    <%= link_to insurances_company_path(company.id, year: Time.zone.now.year), title: "Visualizza assicurazioni." do%>
      <i class="ion-help-buoy icon-small-list"></i>
    <% end %>
    <%= render partial: 'total_costs/total_insurance_costs', locals: {calculator: company.calculator, insurances: company.insurances } %>
  <% else %>
    <%= link_to dashboard_company_path(company.id), id: 'invoices', title: "Visualizza fatture." do%>
      <i class="ion-ios-list icon-small-list"></i>
    <% end %>
    <%= render partial: 'total_costs/total_costs', locals: {calculator: company.calculator, invoices: company.invoices } %>
  <% end %>
</div>

app/views/companies/_form.html.erb
<div class="row">
  <div class="new">
    <%= form_for company do |form| %>
      <% if company.errors.any? %>
        A causa di questi errori non e' stato possibile creare l'azienda:
        <ul>
          <% company.errors.messages.each do |name, error| %>
            <li><%= error[0] %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Nome' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :name, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Indirizzo' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :adress, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Numero' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :number, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Categoria azienda' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.collection_select(:category_id, @category, :id, :name, prompt: "Categorie") %>
        </div>
      </div>
      <div class="row">
        <div class="col span-3-of-3 submit">
          <%= form.submit "Conferma", class: "btn btn-big" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/companies/_gas_station_company.html.erb
<div class="col span-1-of-3 summary">
  <div class="title">
    <h2><%=link_to company.name, company_path(company.id) %></h2>
  </div>
  <%= link_to edit_company_path(company.id), class: 'edit-company', title: "Modifica azienda." do %>
    <i class="ion-ios-compose icon-small-compose"></i>
  <% end %>
  <%= link_to company_path(company.id), class: 'delete-company', title: "Elimina azienda." , method: :delete, data: {confirm: "L'elliminazione di questo veicolo elliminera automaticamente anche le fatture registrate su di esso, si e sicuri di volerlo elliminare?"} do%>
    <i class="ion-ios-trash icon-small-trash"></i>
  <% end %>
  <%= link_to dashboard_company_path(company.id), title: "Visualizza fatture." do%>
    <i class="ion-ios-list icon-small-list"></i>
  <% end %>
  <%= link_to fuel_receipts_company_path(company.id, month: Time.zone.now.month, year: Time.zone.now.year), class: 'fuel_receipts', title: "Visualizza scontrini carburante." do%>
    <i class="ion-funnel icon-small-list"></i>
  <% end %>
  <%= render partial: 'vehicles_fuel_receipts', collection: company.vehicles_refueling, as: :vehicle, locals: { calculator: calculator, company_id: company.id } %>
  <div class="data-summary">
    <div class="row">
      <div class="col span-1-of-2">
        <p id="passive_amont_to_pay">Totale: </p>
      </div>
      <div class="col span-1-of-2 data">
        <p id="total_fuel_receipts_company"><%= company.fuel_receipts_total %> $</p>
      </div>
    </div>
  </div>
</div>

app/views/companies/_insurance_companies.html.erb
<div class="col span-1-of-3 summary">
  <div class="title">
    <h2 id="company_name"><%=link_to company.name, company_path(company.id) %></h2>
  </div>
  <br>
  <%= link_to edit_company_path(company.id), class: 'edit-company', title: "Modifica azienda." do %>
    <i class="ion-ios-compose icon-small-compose"></i>
  <% end %>
  <%= link_to company_path(company.id), class: 'delete-company', title: "Elimina azienda." , method: :delete, data: {confirm: "L'elliminazione di questo veicolo elliminera automaticamente anche le fatture registrate su di esso, si e sicuri di volerlo elliminare?"} do%>
    <i class="ion-ios-trash icon-small-trash"></i>
  <% end %>
  <%= link_to insurances_company_path(company.id, year: Time.zone.now.year), title: "Visualizza assicurazioni." do%>
    <i class="ion-help-buoy icon-small-list"></i>
  <% end %>
  <div class="data-summary">
    <div class="row">
      <div class="col span-1-of-2">
        <h4>Veicoli assicurati:</h4>
      </div>
      <%= render partial: 'vehicles/vehicle_insurance', collection: company.vehicles_insured, as: :vehicle %>
    </div>
  </div>
</div>

app/views/companies/edit.html.erb
<div class="row">
<div class="new">
	<h3>Aggiorna azienda</h3>
</div>
</div>
<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<%=link_to 'Aggiungi azienda', new_company_path %><br>
<br>
<div class="companies">
	<%= render @companies %>
</div>

app/views/companies/new.html.erb
<div class="row">
<div class="new">
	<h3>Aggiugi azienda</h3>
</div>
</div>
<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<div class="row">
  <div class="show">
    <div class="title">
      <h3><%= @company.name %></h3>
    </div>
    <div>
      <h4>Nome</h4>
      <%= @company.name %>
    </div>
    <div>
      <h4>Indirizzo</h4>
      <%= @company.adress %>
    </div>
    <div>
      <h4>Numero</h4>
      <%= @company.number %>
    </div>
    <div>
      <h4>Categoria azienda</h4>
      <%= @company.category_name %>
    </div>
  </div>
</div>