config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'invoice_dashboard#index', as: :authenticated_root
  end

  root to: "accounting#index"

  devise_for :users

  resources :general_expenses, only: [:index] do
    collection do
      get 'active_invoices' => 'general_expenses#active_invoices'
      get 'passive_invoices' => 'general_expenses#passive_invoices'
    end
  end

  resources :fuel_receipts

  resources :invoices, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'invoice_dashboard#index'
      get 'active' => 'invoice_dashboard#active_invoices'
      get 'passive' => 'invoice_dashboard#passive_invoices'
    end

    resources :payments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :insurances do
    resources :receipts, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tickets do
    collection do
      get 'administrative_dashboard' => 'tickets_dashboard#administrative'
      get 'vehicle_dashboard' => 'tickets_dashboard#vehicle'
    end
  end

  resources :categories, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'category_dashboard#index'
    end
    member do
      get 'insurances' => 'insurance_dashboard#category_insurances'
      get 'dashboard' => 'category_dashboard#show'
      get 'passive_invoices' => 'category_dashboard#passive_invoices'
      get 'active_invoices' => 'category_dashboard#active_invoices'
    end
  end

  resources :companies do
    collection do
      get 'dashboard' => 'company_dashboard#index'
    end
    member do
      get 'dashboard' => 'company_dashboard#show'
      get 'insurances' => 'insurance_dashboard#company_insurances'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#company_receipts'
      get 'passive_invoices' => 'company_dashboard#passive_invoices'
      get 'active_invoices' => 'company_dashboard#active_invoices'
    end
  end

  resources :vehicles, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'vehicle_dashboard#index'
    end
    member do
      get 'dashboard' => 'vehicle_dashboard#show'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#vehicle_receipts'
      get 'passive_invoices' => 'vehicle_dashboard#passive_invoices'
      get 'active_invoices' => 'vehicle_dashboard#active_invoices'
    end
  end
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, dependent: :destroy
  has_many :vehicle_field, dependent: :destroy
  has_many :fuel_receipts, dependent: :destroy
  has_many :insurances, dependent: :destroy
  has_many :tickets, dependent: :destroy
  validates :plate, presence: { message: 'Inserire targa del veicolo' }
  validates :type_of_vehicle, presence: { message: 'Inserire tipo di veicolo' }

  def calculator
    Calculator.new
  end

  def fuel_receipts_per_company(comapny_id)
    fuel_receipts.where(company_id: comapny_id).sum(:total).round(2)
  end

  def self.charge_general_expenses
    where(charge_general_expenses: true)
  end

  def self.count_vehicles_general(user_id)
    where(charge_general_expenses: true).where(user_id: user_id).count
  end

  def fuel_receipts_month_total(month = time_now)
    fuel_receipts.total_month(month)
  end

  def fuel_receipts_year_total
    fuel_receipts.total_year
  end

  def passive_invoices_month_total(month = time_now)
    invoices.month_passive_total(month)
  end

  def passive_invoices_year_total
    invoices.year_passive_total
  end

  def total_insurance_month(month = time_now)
    active_insurances = insurances.active
    return 0 unless active_insurances && month.month >= active_insurances.date_of_issue.month
    (active_insurances.total / 12).round(2)
  end

  def insurances_total(month)
    general_insurance_month + total_insurance_month(month)
  end

  def total_insurance_year
    return 0 unless insurances.active
    insurances.active.total.round(2)
  end

  def general_insurance_month
    user_id = self.user_id
    general_insurances = Insurance.general_insurances_total(user_id) / 12
    return 0 if general_insurances.zero?
    general_expenses = Vehicle.count_vehicles_general(user_id)
    (general_insurances / general_expenses).round(2)
  end

  def general_insurance_year
    user_id = self.user_id
    general_insurances = Insurance.general_insurances_total(user_id)
    return 0 if general_insurances.zero?
    general_expences = Vehicle.count_vehicles_general(user_id)
    (general_insurances / general_expences).round(2)
  end

  def general_expenses_month(month = time_now)
    user_id = self.user_id
    general_invoices_total = Invoice.month_general_expenses_total(user_id, month)
    return 0 if general_invoices_total.zero?
    general_expenses = Vehicle.count_vehicles_general(user_id)
    (general_invoices_total / general_expenses).round(2)
  end

  def general_expenses_year
    user_id = self.user_id
    general_invoices_total = Invoice.year_general_expenses_total(user_id)
    return 0 if general_invoices_total.zero?
    general_expenses = Vehicle.count_vehicles_general(user_id)
    (general_invoices_total / general_expenses).round(2)
  end

  def vehicle_field_month(month = time_now)
    return 0 unless vehicle_field
    vehicle_field.month(month).round(2)
  end

  def vehicle_field_year
    return 0 unless vehicle_field
    vehicle_field.year.round(2)
  end

  def total_tickets_month(month = time_now)
    tickets.total_vehicles_month(month)
  end

  def total_tickets_year
    tickets.total_vehicles_year
  end

  def total_administrative_tickets_month(month = time_now)
    user_id = self.user_id
    administrative_tickets_total = Ticket.total_administrative_month(user_id, month)
    return 0 if administrative_tickets_total.zero?
    general_expenses = Vehicle.count_vehicles_general(user_id)
    (administrative_tickets_total / general_expenses).round(2)
  end

  def total_administrative_tickets_year
    user_id = self.user_id
    administrative_tickets_total = Ticket.total_administrative_year(user_id)
    return 0 if administrative_tickets_total.zero?
    general_expenses = Vehicle.count_vehicles_general(user_id)
    (administrative_tickets_total / general_expenses).round(2)
  end

  def specific_month_costs(month = time_now)
    fuel_receipts_month_total(month) +
      passive_invoices_month_total(month) +
      total_insurance_month(month) +
      vehicle_field_month(month) +
      total_tickets_month(month)
  end

  def general_month_costs(month = time_now)
    return 0 unless charge_general_expenses
    general_expenses_month(month) +
      general_insurance_month +
      total_administrative_tickets_month(month)
  end

  def current_month_costs(month = time_now)
    specific_month_costs(month) + general_month_costs(month)
  end

  def specific_year_costs
    fuel_receipts_year_total +
      passive_invoices_year_total +
      total_insurance_year +
      vehicle_field_year +
      total_tickets_year
  end

  def general_year_costs
    return 0 unless charge_general_expenses
    general_expenses_year +
      general_insurance_year +
      total_administrative_tickets_year
  end

  def current_year_costs
    specific_year_costs + general_year_costs
  end

  def time_now
    Time.zone.now
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!

  def new
    @vehicle = Vehicle.new
  end

  def show
    @vehicle_dashboard = VehicleDashboard.new(current_user, params)
    @calculator = Calculator.new
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update(vehicle_params_user_id)
      flash[:success] = 'Mezzo aggiornato'
      redirect_to dashboard_vehicles_path
    else
      render 'edit'
    end
  end

  def destroy
    vehicle = Vehicle.find(params[:id])
    vehicle.destroy
    flash[:success] = 'Mezzo elliminato'
    redirect_after_destroy(current_user_vehicles)
  end

  def create
    @vehicle = Vehicle.new(vehicle_params_user_id)
    if @vehicle.save
      flash[:success] = 'Mezzo aggiunto'
      redirect_to dashboard_vehicles_path
    else
      flash[:error] = 'Mezzo non aggiunto'
      render 'new'
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:plate, :type_of_vehicle, :charge_general_expenses)
  end

  def vehicle_params_user_id
    vehicle_params.merge!(user_id: current_user.id)
  end

  def vehicle_id
    params[:id]
  end
end

app/views/vehicles/_form.html.erb
<div class="row">
  <div class="new">
    <%= form_for vehicle do |form| %>
      <% if vehicle.errors.any? %>
        A causa di questi errori non e' stato possibile creare il veicolo:
        <ul>
          <% vehicle .errors.messages.each do |name, error| %>
            <li><%= error[0] %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Targa' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :plate, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Tipo mezzo' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :type_of_vehicle, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
        </div>
        <div class="gas-station col span-2-of-3">
          <%= form.label :charge_general_expences do %>
            <%= form.check_box(:charge_general_expenses)  %> Imputazione delle spese generali
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col span-3-of-3 submit">
          <%= form.submit "Conferma", class: "btn btn-big" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/vehicles/_specific_vehicles.html.erb
<div class="row">
  <div class="col span-1-of-3">
    <%= form.label 'Mezzo' %>
  </div>
  <div class="col span-2-of-3">
    <%= form.collection_select(:vehicle_id, @vehicles, :id, :plate, prompt: 'Selezionare veicolo', selected: form.object.vehicle_id) %>
  </div>
</div>

app/views/vehicles/_vehicle.html.erb
<div class="col span-1-of-3 summary">
  <div class="title">
    <h2 id='vehicle_plate'><%=link_to vehicle.plate, vehicle_path(vehicle.id, month: Time.zone.now.month, year: Time.zone.now.year) %></h2>
  </div>
  <%= link_to edit_vehicle_path(vehicle.id), class: 'edit-vehicle', title: "Modifica veicolo." do %>
    <i class="ion-ios-compose icon-small-compose"></i>
  <% end %>
  <%= link_to vehicle_path(vehicle.id), class: 'delete-vehicle', title: "Elimina veicolo." , method: :delete, data: {confirm: "L'elliminazione di questo veicolo elliminera automaticamente anche le fatture registrate su di esso, si e sicuri di volerlo elliminare?"} do%>
    <i class="ion-ios-trash icon-small-trash"></i>
  <% end %>
  <%= link_to dashboard_vehicle_path(vehicle.id), id: 'invoices', title: "Visualizza fatture." do%>
    <i class="ion-ios-list icon-small-list"></i>
  <% end %>
  <%= link_to fuel_receipts_vehicle_path(vehicle.id, month: Time.zone.now.month, year: Time.zone.now.year), id: 'fuel_receipts', title: "Visualizza scontrini carburante." do%>
    <i class="ion-funnel icon-small-list"></i>
  <% end %>
  <%= render partial: "total_costs/total_costs_vehicle", locals: { vehicle: vehicle, calculator: vehicle.calculator, fuel_receipts: vehicle.fuel_receipts } %>
</div>

app/views/vehicles/_vehicle_insurance.html.erb
<% if vehicle.insurances.active %>
  <div class="col span-1-of-2 data">
    <p id='vehicle_plate'><%= link_to vehicle.plate, vehicle_path(vehicle.id, month: Time.zone.now.month, year: Time.zone.now.year) %></p>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="row">
<div class="new">
	<h3>Aggiorna veicolo</h3>
</div>
</div>
<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/new.html.erb
<div class="row">
<div class="new">
	<h3>Aggiungi veicolo</h3>
</div>
</div>
<%= render 'form', vehicle: @vehicle %>

app/views/vehicles/show.html.erb
<div class="row">
  <div class="show">
    <div class="col span-1-of-2">
      <div class="row">
        <div class="invoices-by-year">
          <h3><%= params[:month]%>/<%= params[:year]%></h3>
          <h4><%= previos_month_costs(@vehicle_dashboard) %></h4>
          <h4><%= next_month_costs(@vehicle_dashboard) %></h4>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-2">
          <h4>Fatture Passive</h4>
        </div>
        <div class="col span-1-of-2 data">
          <p id="current_month_costs"><%= @vehicle_dashboard.total_month_passive %></p>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-2">
          <h4>Scontrini Carburante</h4>
        </div>
        <div class="col span-1-of-2 data">
          <p id="current_month_costs"><%= @vehicle_dashboard.total_fuel_receipts_month %></p>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-2">
          <h4>Spese generali</h4>
        </div>
        <div class="col span-1-of-2 data">
          <p id="current_month_costs"><%= @vehicle_dashboard.vehicle_general_expenses %></p>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-2">
          <h4>Assicurazioni</h4>
        </div>
        <div class="col span-1-of-2 data">
          <p id="current_month_costs"><%= @vehicle_dashboard.vehicle_insurances_month %></p>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-2">
          <h4>Costi totali <%= params[:month]%>/<%= params[:year]%></h4>
        </div>
        <div class="col span-1-of-2 data">
          <p id="current_month_costs"><%= @vehicle_dashboard.total_costs_month %></p>
        </div>
      </div>
    </div>
    <div class="col span-1-of-2">
      <div class="title">
        <h3><%= @vehicle_dashboard.plate %></h3>
      </div>
      <div>
        <h4>Targa</h4>
        <%= @vehicle_dashboard.plate %>
      </div>
      <div>
        <h4>Tipo mezzo</h4>
        <%= @vehicle_dashboard.type_of_vehicle %>
      </div>
      <%if @vehicle_dashboard.insurances.active %>
        <div>
          <h4>Scadenza assicurazione</h4>
          <p id="insurance_deadline"><%= @vehicle_dashboard.insurances.active.deadline.strftime("%d-%m-%Y") %></p>
        </div>
        <div>
          <h4>Scadenza pagamento assicurazione</h4>
          <p id="insurance_payment_deadline"><%= @vehicle_dashboard.insurances.active.payment_date %></p>
        </div>
        <div>
          <h4>Assicurazione</h4>
          <p><%= link_to @vehicle_dashboard.insurances.active.serial_of_contract, insurance_path(@vehicle_dashboard.insurances.active.id) %></p>
        </div>
      <%end%>
    </div>
  </div>
</div>