config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root 'invoice_dashboard#index', as: :authenticated_root
  end

  root to: "accounting#index"

  devise_for :users

  resources :general_expenses, only: [:index] do
    collection do
      get 'active_invoices' => 'general_expenses#active_invoices'
      get 'passive_invoices' => 'general_expenses#passive_invoices'
    end
  end

  resources :fuel_receipts

  resources :invoices, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'invoice_dashboard#index'
      get 'active' => 'invoice_dashboard#active_invoices'
      get 'passive' => 'invoice_dashboard#passive_invoices'
    end

    resources :payments, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :insurances do
    resources :receipts, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :tickets do
    collection do
      get 'administrative_dashboard' => 'tickets_dashboard#administrative'
      get 'vehicle_dashboard' => 'tickets_dashboard#vehicle'
    end
  end

  resources :categories, only: [:new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'category_dashboard#index'
    end
    member do
      get 'insurances' => 'insurance_dashboard#category_insurances'
      get 'dashboard' => 'category_dashboard#show'
      get 'passive_invoices' => 'category_dashboard#passive_invoices'
      get 'active_invoices' => 'category_dashboard#active_invoices'
    end
  end

  resources :companies do
    collection do
      get 'dashboard' => 'company_dashboard#index'
    end
    member do
      get 'dashboard' => 'company_dashboard#show'
      get 'insurances' => 'insurance_dashboard#company_insurances'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#company_receipts'
      get 'passive_invoices' => 'company_dashboard#passive_invoices'
      get 'active_invoices' => 'company_dashboard#active_invoices'
    end
  end

  resources :vehicles, only: [:show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'dashboard' => 'vehicle_dashboard#index'
    end
    member do
      get 'dashboard' => 'vehicle_dashboard#show'
      get 'fuel_receipts' => 'fuel_receipt_dashboard#vehicle_receipts'
      get 'passive_invoices' => 'vehicle_dashboard#passive_invoices'
      get 'active_invoices' => 'vehicle_dashboard#active_invoices'
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, dependent: :destroy
  has_many :insurances, dependent: :destroy
  has_many :companies, dependent: :destroy
  validates :name, presence: { message: 'Inserire il nome della categoria' }
  validates :type_of, presence: { message: 'Selezionare tipologia' }

  def calculator
    Calculator.new
  end

  def self.gas_station_id
    gas_station.id if gas_station
  end

  def self.gas_station
    find_by(type_of: 2)
  end

  def self.insurance_id
    insurance.id if insurance
  end

  def insurance?
    return true if self.type_of == 3
    false
  end

  def self.insurance
    find_by(type_of: 3)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Categoria modificata'
      redirect_to dashboard_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:success] = 'Categoria elliminata'
    redirect_after_destroy(current_user_categories)
  end

  def create
    @category = Category.new(category_params_user_id)
    if @category.save
      flash[:success] = 'Categoria aggiunta'
      redirect_to dashboard_categories_path
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :type_of)
  end

  def category_params_user_id
    category_params.merge!(user_id: current_user[:id])
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def gas_station?
    current_user.categories.gas_station == nil ? false : true
  end
end

app/helpers/category_helper.rb
module CategoryHelper
  def category(category_id)
    Category.find(category_id).category
  end
end

app/views/categories/_category.html.erb
<% if category.insurance? %>
  <%= render 'categories/insurance_category', category: category%>
<% else %>
  <%= render 'categories/normal_category', category: category %>
<% end %>

app/views/categories/_form.html.erb
<div class="row">
  <div class="new">
    <%= form_for category do |form| %>
      <% if category.errors.any? %>
        A causa di questi errori non e' stato possibile creare la categoria:
        <ul>
          <% category.errors.messages.each do |name, error| %>
            <li><%= error[0] %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Categoria' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.text_field :name, require: true %>
        </div>
      </div>
      <div class="row">
        <div class="col span-1-of-3">
          <%= form.label 'Selezionare tipologia' %>
        </div>
        <div class="col span-2-of-3">
          <%= form.select(:type_of, options_for_select([["Altro", 1], ["Benzinaii", 2], ["Assicurazioni", 3]], selected: form.object.type_of )) %>
        </div>
      </div>
      <div class="row">
        <div class="col span-3-of-3 submit">
          <%= form.submit "Conferma", class: "btn btn-big" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_insurance_category.html.erb
<div class="col span-1-of-3 summary">
  <div class="title">
    <h2 id="category_name"><%=category.name%></h2>
  </div>
  <%= link_to edit_category_path(category.id), title: "Modifica categoria." do %>
    <i class="ion-ios-compose icon-small-compose"></i>
  <% end %>
  <%= link_to category_path(category.id), title: "Elimina categoria.", class: 'delete-category', method: :delete, data: {confirm: "L'elliminazione di questo veicolo elliminera automaticamente anche le assicurazioni registrate su di esso, si e sicuri di volerlo elliminare?"} do%>
    <i class="ion-ios-trash icon-small-trash"></i>
  <% end %>
  <%= link_to insurances_category_path(category.id, year: Time.zone.now.year), title: "Visualizza assicurazioni." do%>
    <i class="ion-help-buoy icon-small-list"></i>
  <% end %>
  <%= render partial: 'total_costs/total_insurance_costs', locals: { calculator: category.calculator, insurances: category.insurances } %>
</div>

app/views/categories/_normal_category.html.erb
<div class="col span-1-of-3 summary">
  <div class="title">
    <h2 id="category_name"><%=category.name%></h2>
  </div>
  <%= link_to edit_category_path(category.id), title: "Modifica categoria." do %>
    <i class="ion-ios-compose icon-small-compose"></i>
  <% end %>
  <%= link_to category_path(category.id), title: "Elimina categoria.", class: 'delete-category', method: :delete, data: {confirm: "L'elliminazione di questo veicolo elliminera automaticamente anche le fatture registrate su di esso, si e sicuri di volerlo elliminare?"} do%>
    <i class="ion-ios-trash icon-small-trash"></i>
  <% end %>
  <%= link_to dashboard_category_path(category.id), id: 'invoices', title: "Visualizza fatture." do%>
    <i class="ion-ios-list icon-small-list"></i>
  <% end %>
  <%= render partial: 'total_costs/total_costs', locals: { calculator: category.calculator, invoices: category.invoices } %>
</div>

app/views/categories/edit.html.erb
<div class="row">
<div class="new">
	<h3>Modifica categoria</h3>
</div>
</div>
<%= render 'form', category: @category %>

app/views/categories/new.html.erb
<div class="row">
<div class="new">
	<h3>Aggiungi categoria</h3>
</div>
</div>
<%= render 'form', category: @category %>